### ISSUE TITLE
Domaci úkoly z lekce 7 a 8

### ISSUE THREAD

**Issue by Baruli** [Baruli/python-032021#1]
Prosim o opravu domácích úkolu k lekci 7 a 8.

**Comment by Baruli** [comment]
@pesikj Bob mi zatim neodsouhlasil spolupraci, tak pridavam aspon Tebe, aby bylo jasne, ze jsem ukoly odevzdala.

**Comment by Baruli** [comment]
@redguy Prosim o pravu domacich ukolu lekce 7 a 8

**Comment by redguy** [comment]
oboje v poradku, dobra prace!
