### ISSUE TITLE
Domaci ukol z lekce 9

### ISSUE THREAD

**Issue by Baruli** [Baruli/python-032021#2]
@pesikj @redguy Prosim o opravu domácích úkolu z lekce 9

**Comment by redguy** [comment]
Vyborne, jen poznamka k te analyze vody: kdyz hledas nejlepsi pocet sousedu pro klasifikator, testujes hodnoty `[1,3,5,7,9]`. Kdyz se podivas na hodnoty `precision` pro jednotlive pocty sousedu, je videt, ze postupne roste. Nakonec jsi vybrala tu s nejvyssi presnosti (9), coz je skoro spravne. Problem je, ze pro jeste vyssi hodnoty poctu sousedu dosahnes jeste vyssi presnosti:
```
1 0.54421768707483
3 0.56
5 0.5873015873015873
7 0.5564516129032258
9 0.6090909090909091
11 0.5943396226415094
13 0.6382978723404256
15 0.6333333333333333
17 0.6129032258064516
```
V tvem pripade by spravny postup byl: zkusim hodnoty 1-9 -> vidim, ze presnost porad roste -> vyzkousim jeste dalsi, vyssi hodnoty -> prestanu v okamziku, kdy presnost uz bud roste jen malinko, nebo dokonce klesa.

Nicmene, to je jen drobnost, ukol beru jako skvele splneny 8)

**Comment by Baruli** [comment]
@redguy To je skvělý point, dekuju, ze si me na nej upozornil. Budu se tvým postupem ridit i v budoucnu.
